### ISSUE TITLE
Survey edits

### ISSUE THREAD

**Issue by ebreimer** [ebreimer/siena-iat-2016#14]
All survey questions must have a "Prefer Not to Answer" option

The gender question should have the options: Male, Female, Transgender, Other, Prefer Not to Answer

**Comment by brendon-boldt** [comment]
Okay; I just had it as all of the survey questions being optional. I can add that to the genders.

**Comment by ebreimer** [comment]
The IRB requests that "Prefer Not to Answer" must be there explicitly so it is clear that responding is not required.  Also, it helps us differentiate those who prefer not to respond vs. those who just don't answer the question perhaps by mistake.
