### ISSUE TITLE
Disagreeing on Informed Consent

### ISSUE THREAD

**Issue by zwhile** [ebreimer/siena-iat-2016#16]
Choosing the "DISAGREE" option on the informed consent form takes you to http://sienasellbacks.com/exit.php which is a white "Not Found" page.  It also switches the URL back to sienasellbacks.com which we may not want (this may be because of the current URL it has).

**Comment by brendon-boldt** [comment]
This is a bug just with the test repository. This does not happen with the actual repository. Thanks for reporting it, though.
