### ISSUE TITLE
Opening Infographic in New Tab

### ISSUE THREAD

**Issue by zwhile** [ebreimer/siena-iat-2016#17]
If you click the "proceed" button and open it in a new tab (as many times as you like), it randomly chooses which infographic you are shown each time.  This could let someone choose which cheat method they are recorded as using, which may not be good.  Once you choose "Continue to IAT" on one of the tabs, all other infographic tabs will return an error when attempting to continue.

**Comment by brendon-boldt** [comment]
Fixed. Test repository will be updated before tomorrow morning.
