### ISSUE TITLE
Received Incorrect Cheat Type

### ISSUE THREAD

**Issue by zwhile** [ebreimer/siena-iat-2016#23]
First IAT attempt: 
- Score of 0.5
- Shown infographic suggesting that I associate _Females_ with Computer Science (and related strategy).  

Second IAT attempt: 
- Score of 0.51 
- Ending statement says that my score suggests I associate _Males_ with Computer Science.  

Perhaps the infographics simply need switched (this occurred with cheat_type=1).

**Comment by brendon-boldt** [comment]
Fixed.
