### ISSUE TITLE
Required to Scroll Down for Infographic

### ISSUE THREAD

**Issue by zwhile** [ebreimer/siena-iat-2016#24]
This isn't a huge issue, but when shown an infographic I had to scroll down a bit to hit the continue button which contrasts the rest of the IAT.  Is there a way to make it so that the picture always resizes such that users never have to scroll down to click the button to continue?

**Comment by brendon-boldt** [comment]
Text size is more important than scrolling, so, in the event that the subject's screen size is small or has a high pixel density, we want the infographic to be as large as possible. This means that vertical scrolling will likely be required.
